---
- hosts: kubernetes-master
  become: yes
  vars_files:
  - app_env_variables
  tasks:

  - name: Add Helm Repo
    shell: helm repo add helm https://csudharsan.jfrog.io/artifactory/helm --username admin --password AP5sHFBRdT4tZ1ui1z1JWi6UbNU

  - name: Update Helm Repo
    shell: helm repo update
  
  - name: Create Secret 
    shell: sudo kubectl create secret docker-registry regcred --docker-server={{jfrogrepo}} --docker-username={{jfroguser}} --docker-password={{jfrogpass}} --docker-email={{jfrogemail}}
    
  - name: Install Helm Chart
    shell: helm install helm/simplewebapp-chart --generate-name
