---
- hosts: kubernetes-worker
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src=/home/jenkins/{{ token_file }} dest=/home/jenkins/join_token

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat /home/jenkins/join_token | tail -2 > out.sh
     sh out.sh
